restrictedRepos:
  # You can exclude certain repos from safe-settings processing
  # If no file is specified, then the following repositories - 'admin', '.github', 'safe-settings' are exempted by default
  exclude:
    - '^\.github$'
    - '^jenkins-library$'
    - '^cobra$'
    - '^delivery-*'
    - '^ocm-gear$'
    - '^prometheus$'
    - '^vscode-ocm-tools$' # archived
    - '^ocm-k8s-toolkit$' # archived
    - '^service-model$' # archived
  # Alternatively you can only include certain repos
  #include: ['^ocm-*']
